sudo: required
services:
  - docker

before_install:
  - docker build -t dinuwan97/aws_deployment_microservices -f Dockerfile.dev .

script:
  - docker run dinuwan97/aws_deployment_microservices npm run test -- --coverage